### ISSUE TITLE
does supports backgroundColor?

### ISSUE THREAD

**Issue by USTHzhanglu** [sapegin/vscode-todo-tomorrow#5]
in settings.json, it`s can config like this
```json
      "dark": {
        "color": "#dcd5c0",
        "backgroundColor": "#0xff0000"
      },
```
but seems not useful
![image](https://github.com/user-attachments/assets/2b913476-64f7-4bf2-8b72-789b370fa256)

**Comment by sapegin** [comment]
Feel free to send a pull request with fix.

**Comment by USTHzhanglu** [comment]
> Feel free to send a pull request with fix.

seems a mistaken :) i make it `#0xff0000`, remove `0x` and it`s work good.

and seems not support `0xff0000`
![image](https://github.com/user-attachments/assets/a4957be6-8314-4469-818a-7e5951c7fa39)

a good extension.
